# Generated by Django 2.2.19 on 2023-02-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('low_price', models.PositiveIntegerField(blank=True)),
                ('high_price', models.PositiveIntegerField(blank=True)),
                ('parent_id', models.PositiveIntegerField(blank=True)),
                ('delta', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='goods.Product')),
            ],
        ),
    ]
