# Generated by Django 2.2.19 on 2023-02-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='query',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='shard',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
